test: Add initial e2e test framework

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -56,24 +56,20 @@ jobs:
 
   e2e-test:
     runs-on: ubuntu-22.04
+    permissions:
+      checks: write
     steps:
       - name: Check out code
         uses: actions/checkout@v4
-
-      - name: "Check e2e tests exist"
-        id: check_e2e_tests_exist
-        uses: andstor/file-existence-action@v3
         with:
-          files: "test/e2e/**"
+          fetch-depth: 0
 
-      - if: steps.check_e2e_tests_exist.outputs.files_exists == 'true'
-        name: Install devbox
+      - name: Install devbox
         uses: jetpack-io/devbox-install-action@v0.8.0
         with:
           enable-cache: true
 
-      - if: steps.check_e2e_tests_exist.outputs.files_exists == 'true'
-        name: Go cache
+      - name: Go cache
         uses: actions/cache@v4
         with:
           path: |
@@ -83,21 +79,18 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-go-
 
-      - if: steps.check_e2e_tests_exist.outputs.files_exists == 'true'
-        name: Build and install on KinD
-        run: devbox run -- make dev.run-on-kind
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - if: steps.check_e2e_tests_exist.outputs.files_exists == 'true'
-        name: Run e2e tests
+      - name: Run e2e tests
         run: devbox run -- make e2e-test
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - if: steps.check_e2e_tests_exist.outputs.files_exists == 'true' && always()
-        name: Cleanup KinD cluster
-        run: devbox run -- make kind.delete
+      - if: success() || failure() # always run even if the previous step fails
+        name: Publish e2e test report
+        uses: mikepenz/action-junit-report@v4
+        with:
+          report_paths: 'junit-e2e.xml'
+          check_name: 'e2e test report'
+          detailed_summary: true
 
   lint-go:
     runs-on: ubuntu-22.04
